---
name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.2', '25.0']
        rebar3: ['3.22.0']
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Check formatting
        run: rebar3 steamroll --check

      - name: Run unit tests
        run: rebar3 ct

      - name: Run static code analysis checks
        run: |
          rebar3 dialyzer
